package cl.minvu.solicitudes.solicitudes;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(c7035148def3a818b0da2b7b1695df9d)
 */
@org.kie.api.definition.type.Label(value = "stock de inventario")
public class Stock  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean flag;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer stock;

    public Stock() {
    }

    public Stock(java.lang.Integer stock, java.lang.Boolean flag) {
        this.stock = stock;
        this.flag = flag;
    }


    
    public java.lang.Boolean getFlag() {
        return this.flag;
    }

    public void setFlag(java.lang.Boolean flag) {
        this.flag = flag;
    }
    
    public java.lang.Integer getStock() {
        return this.stock;
    }

    public void setStock(java.lang.Integer stock) {
        this.stock = stock;
    }
}